name: AutoReboot
author: Mexipajas
website: https://github.com/Mexipajas/AutoReboot

version: 0.0.2-MXPJS
main: AutoReboot\Main
api: 5.32.1

permissions:
  autoreboot.command.setreboottime:
    description: Permite usar el comando /setreboottime
    default: op
